name: Deploy Telegram PHP Backend to FTP

on:
  push:
    paths:
      - 'telegram/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Generate .env file from secrets
      run: |
        mkdir -p telegram/log telegram/uploads telegram/screenshots
        echo "BASE_URL=${{ secrets.BASE_URL }}" > telegram/.env
        echo "SERVER_URL=${{ secrets.BASE_URL }}/api.php" >> telegram/.env
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> telegram/.env
        echo "WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}" >> telegram/.env
        echo "ADMIN_CHAT_ID=${{ secrets.ADMIN_CHAT_ID }}" >> telegram/.env

        echo "DB_HOST=${{ secrets.DB_HOST }}" >> telegram/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> telegram/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> telegram/.env
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> telegram/.env

        echo "SECRET_TOKEN=1" >> telegram/.env
        echo "ENCRYPTION_KEY=dGVzdF9rZXk=" >> telegram/.env  # base64 of "test_key"

    - name: Upload to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: telegram/
        server-dir: ${{ secrets.FTP_PATH }}
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/*
